#' Plot a dimensionality reduced trajectory
#'
#' @param original_object An object generated by \code{wrap_data} or \code{dimred_trajectory}.
#' @param new_object An object generated by \code{wrap_data} or \code{dimred_trajectory}.
#' @inheritParams plot_default
#'
#' @export
#'
#' @include plot_default.R
plot_combined <- dynutils::inherit_default_params(
  list(plot_default),
  function(
    original_object,
    new_object,
    transition_size,
    cell_size,
    milestone_size,
    arrow_length,
    plot_label,
    plot_milestones
  ) {
    original_dimred <- check_or_perform_dimred(original_object)
    new_dimred <- check_or_perform_dimred(new_object)

    colour_milestones <- original_dimred$space_milestones %$%
      set_names(colour, milestone_id)
    colour_cells <- original_dimred$space_samples %$%
      set_names(colour, cell_id)

    plot_default(
      new_dimred,
      colour_milestones = colour_milestones,
      colour_cells = colour_cells,
      transition_size = transition_size,
      cell_size = cell_size,
      milestone_size = milestone_size,
      arrow_length = arrow_length,
      plot_label = plot_label,
      plot_milestones = plot_milestones
    ) +
      ggtitle(paste0(original_object$id, " vs. ", new_object$id))
  }
)
